<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterKementerian;

class MasterKementerianSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['nama_kementerian' => 'Kementrian Koordinator Bidang Politik dan Keamanan', 'kode_umap' => 1, 'urutan' => 1],
            ['nama_kementerian' => 'Kementrian Koordinator Bidang Hukum, Hak Asasi Manusia, Imigrasi, dan  Pemasyarakatan', 'kode_umap' => 2, 'urutan' => 2],
            ['nama_kementerian' => 'Kementrian Koordinator Bidang Perekonomian', 'kode_umap' => 3, 'urutan' => 3],
            ['nama_kementerian' => 'Kementrian Koordinator Bidang Pembangunan Manusia dan Kebudayaan', 'kode_umap' => 4, 'urutan' => 4],
            ['nama_kementerian' => 'Kementrian Koordinator Bidang Infrastruktur dan Pembangunan Kewilayahan', 'kode_umap' => 5, 'urutan' => 5],
            ['nama_kementerian' => 'Kementrian Koordinator Bidang Pemberdayaan Masyarakat', 'kode_umap' => 6, 'urutan' => 6],
            ['nama_kementerian' => 'Kementrian Koordinator Bidang Pangan', 'kode_umap' => 7, 'urutan' => 7],
            ['nama_kementerian' => 'Kementrian Sekretaris Negara', 'kode_umap' => 8, 'urutan' => 8],
            ['nama_kementerian' => 'Kementrian Dalam Negeri', 'kode_umap' => 9, 'urutan' => 9],
            ['nama_kementerian' => 'Kementrian Luar Negeri', 'kode_umap' => 10, 'urutan' => 10],
            ['nama_kementerian' => 'Kementrian Pertahanan', 'kode_umap' => 11, 'urutan' => 11],
            ['nama_kementerian' => 'Kementrian Agama', 'kode_umap' => 12, 'urutan' => 12],
            ['nama_kementerian' => 'Kementrian Hukum', 'kode_umap' => 13, 'urutan' => 13],
            ['nama_kementerian' => 'Kementrian Keuangan', 'kode_umap' => 14, 'urutan' => 14],
            ['nama_kementerian' => 'Kementrian Sosial', 'kode_umap' => 15, 'urutan' => 15],
            ['nama_kementerian' => 'Kementrian Infrastruktur dan Pembangunan Kewilayahan', 'kode_umap' => 16, 'urutan' => 16],
            ['nama_kementerian' => 'Kementrian Perdagangan', 'kode_umap' => 17, 'urutan' => 17],
            ['nama_kementerian' => 'Kementrian Pertanian', 'kode_umap' => 18, 'urutan' => 18],
            ['nama_kementerian' => 'Kementrian Lingkungan Hidup', 'kode_umap' => 19, 'urutan' => 19],
            ['nama_kementerian' => 'Kementrian Komunikasi dan Digital', 'kode_umap' => 20, 'urutan' => 20],
            ['nama_kementerian' => 'Kementrian Kesehatan', 'kode_umap' => 21, 'urutan' => 21],
            ['nama_kementerian' => 'Kementrian Perhubungan', 'kode_umap' => 22, 'urutan' => 22],
            ['nama_kementerian' => 'Kementrian Pendidikan Dasar dan Menengah', 'kode_umap' => 23, 'urutan' => 23],
            ['nama_kementerian' => 'Kementrian Pendidikan Tinggi, Sains, dan Teknologi', 'kode_umap' => 24, 'urutan' => 24],
            ['nama_kementerian' => 'Kementrian Kebudayaan', 'kode_umap' => 25, 'urutan' => 25],
            ['nama_kementerian' => 'Kementrian Ekonomi Kreatif', 'kode_umap' => 26, 'urutan' => 26],
            ['nama_kementerian' => 'Kementrian Pariwisata', 'kode_umap' => 27, 'urutan' => 27],
            ['nama_kementerian' => 'Kementrian Ketenagakerjaan', 'kode_umap' => 28, 'urutan' => 28],
            ['nama_kementerian' => 'Kementrian Perlindungan Pekerja Migran Indonesia', 'kode_umap' => 29, 'urutan' => 29],
            ['nama_kementerian' => 'Kementrian Pemberdayaan Perempuan dan Perlindungan Anak', 'kode_umap' => 30, 'urutan' => 30],
            ['nama_kementerian' => 'Kementrian Kependudukan dan Pembangunan Keluarga', 'kode_umap' => 31, 'urutan' => 31],
            ['nama_kementerian' => 'Kementrian Perumahan dan Kawasan Permukiman', 'kode_umap' => 32, 'urutan' => 32],
            ['nama_kementerian' => 'Kementrian Desa dan Pembangunan Daerah Tertinggal', 'kode_umap' => 33, 'urutan' => 33],
            ['nama_kementerian' => 'Kementrian Transmigrasi', 'kode_umap' => 34, 'urutan' => 34],
            ['nama_kementerian' => 'Kementrian Kelautan dan Perikanan', 'kode_umap' => 35, 'urutan' => 35],
            ['nama_kementerian' => 'Kementrian Pekerjaan Umum', 'kode_umap' => 36, 'urutan' => 36],
            ['nama_kementerian' => 'Kementrian Energi dan Sumber Daya Mineral', 'kode_umap' => 37, 'urutan' => 37],
            ['nama_kementerian' => 'Kementrian Investasi dan Hilirisasi', 'kode_umap' => 38, 'urutan' => 38],
            ['nama_kementerian' => 'Kementrian Badan Usaha Milik Negara', 'kode_umap' => 39, 'urutan' => 39],
            ['nama_kementerian' => 'Kementrian Koperasi', 'kode_umap' => 40, 'urutan' => 40],
            ['nama_kementerian' => 'Kementrian Usaha Mikro, Kecil, dan Menengah', 'kode_umap' => 41, 'urutan' => 41],
            ['nama_kementerian' => 'Kementrian Perindustrian', 'kode_umap' => 42, 'urutan' => 42],
            ['nama_kementerian' => 'Kementrian Peternakan', 'kode_umap' => 43, 'urutan' => 43],
            ['nama_kementerian' => 'Kementrian Kehutanan', 'kode_umap' => 44, 'urutan' => 44],
            ['nama_kementerian' => 'Kementrian Pangan', 'kode_umap' => 45, 'urutan' => 45],
            ['nama_kementerian' => 'Kementrian Hukum, Hak Asasi Manusia, Imigrasi, dan Pemasyarakatan', 'kode_umap' => 46, 'urutan' => 46],
            ['nama_kementerian' => 'Kementrian Komunikasi', 'kode_umap' => 47, 'urutan' => 47],
            ['nama_kementerian' => 'Kementrian Digital', 'kode_umap' => 48, 'urutan' => 48],
            ['nama_kementerian' => 'Kementrian Imigrasi', 'kode_umap' => 49, 'urutan' => 49],
            ['nama_kementerian' => 'Kementrian Pemasyarakatan', 'kode_umap' => 50, 'urutan' => 50],
            ['nama_kementerian' => 'Kementrian Hukum dan HAM', 'kode_umap' => 51, 'urutan' => 51],
            ['nama_kementerian' => 'Kementrian Hukum dan Hak Asasi Manusia', 'kode_umap' => 52, 'urutan' => 52],
            ['nama_kementerian' => 'Kementrian Pembangunan', 'kode_umap' => 53, 'urutan' => 53],
            ['nama_kementerian' => 'Kementrian Infrastruktur', 'kode_umap' => 54, 'urutan' => 54],
            ['nama_kementerian' => 'Kementrian Pemberdayaan Masyarakat', 'kode_umap' => 55, 'urutan' => 55],
            ['nama_kementerian' => 'Kementrian Ketenagakerjaan dan Perlindungan Tenaga Kerja', 'kode_umap' => 56, 'urutan' => 56],
            ['nama_kementerian' => 'Kementrian Koordinator dan Sekretaris Kabinet', 'kode_umap' => 57, 'urutan' => 57],
            ['nama_kementerian' => 'Kementrian Sekretaris Kabinet', 'kode_umap' => 58, 'urutan' => 58],
            ['nama_kementerian' => 'Kementrian Koordinator Pembangunan Manusia', 'kode_umap' => 59, 'urutan' => 59],
            ['nama_kementerian' => 'Kementrian Koordinator Infrastruktur', 'kode_umap' => 60, 'urutan' => 60],
            ['nama_kementerian' => 'Kementrian Koordinator Ekonomi Kreatif', 'kode_umap' => 61, 'urutan' => 61],
            ['nama_kementerian' => 'Kementrian Koordinator Pariwisata', 'kode_umap' => 62, 'urutan' => 62],
            ['nama_kementerian' => 'Kementrian Koordinator Pendidikan', 'kode_umap' => 63, 'urutan' => 63],
            ['nama_kementerian' => 'Kementrian Koordinator Sosial', 'kode_umap' => 64, 'urutan' => 64],
            ['nama_kementerian' => 'Kementrian Koordinator Perumahan', 'kode_umap' => 65, 'urutan' => 65],
            ['nama_kementerian' => 'Kementrian Koordinator Kelautan', 'kode_umap' => 66, 'urutan' => 66],
            ['nama_kementerian' => 'Kementrian Koordinator Kehutanan', 'kode_umap' => 67, 'urutan' => 67],
            ['nama_kementerian' => 'Kementrian Koordinator Pekerjaan Umum', 'kode_umap' => 68, 'urutan' => 68],
            ['nama_kementerian' => 'Kementrian Koordinator Energi', 'kode_umap' => 69, 'urutan' => 69],
            ['nama_kementerian' => 'Kementrian Koordinator Investasi', 'kode_umap' => 70, 'urutan' => 70],
            ['nama_kementerian' => 'Kementrian Koordinator BUMN', 'kode_umap' => 71, 'urutan' => 71],
            ['nama_kementerian' => 'Kementrian Koordinator Koperasi', 'kode_umap' => 72, 'urutan' => 72],
            ['nama_kementerian' => 'Kementrian Koordinator UMKM', 'kode_umap' => 73, 'urutan' => 73],
            ['nama_kementerian' => 'Kementrian Koordinator Perindustrian', 'kode_umap' => 74, 'urutan' => 74],
            ['nama_kementerian' => 'Kementrian Koordinator Peternakan', 'kode_umap' => 75, 'urutan' => 75],
            ['nama_kementerian' => 'Kementrian Koordinator Pangan dan Pertanian', 'kode_umap' => 76, 'urutan' => 76],
            ['nama_kementerian' => 'Kementrian Koordinator Hukum dan HAM', 'kode_umap' => 77, 'urutan' => 77],
            ['nama_kementerian' => 'Kementrian Koordinator Komunikasi Digital', 'kode_umap' => 78, 'urutan' => 78],
            ['nama_kementerian' => 'Kementrian Koordinator Kesehatan', 'kode_umap' => 79, 'urutan' => 79],
            ['nama_kementerian' => 'Kementrian Koordinator Pendidikan Tinggi', 'kode_umap' => 80, 'urutan' => 80],
            ['nama_kementerian' => 'Kementrian Koordinator Kebudayaan', 'kode_umap' => 81, 'urutan' => 81],
            ['nama_kementerian' => 'Kementrian Koordinator Ekonomi Kreatif dan Pariwisata', 'kode_umap' => 82, 'urutan' => 82],
            ['nama_kementerian' => 'Kementrian Koordinator Perlindungan Pekerja Migran Indonesia', 'kode_umap' => 83, 'urutan' => 83],
            ['nama_kementerian' => 'Kementrian Koordinator Kependudukan dan Pembangunan Keluarga', 'kode_umap' => 84, 'urutan' => 84],
            ['nama_kementerian' => 'Kementrian Koordinator Pemberdayaan Perempuan', 'kode_umap' => 85, 'urutan' => 85],
            ['nama_kementerian' => 'Kementrian Koordinator Transmigrasi', 'kode_umap' => 86, 'urutan' => 86],
            ['nama_kementerian' => 'Kementrian Koordinator Desa', 'kode_umap' => 87, 'urutan' => 87],
            ['nama_kementerian' => 'Kementrian Koordinator Perumahan dan Kawasan Permukiman', 'kode_umap' => 88, 'urutan' => 88],
            ['nama_kementerian' => 'Kementrian Koordinator Pangan (cadangan)', 'kode_umap' => 89, 'urutan' => 89],
            ['nama_kementerian' => 'Kementrian Koordinator Pemerintahan', 'kode_umap' => 90, 'urutan' => 90],
            ['nama_kementerian' => 'Kementrian Koordinator Agama', 'kode_umap' => 91, 'urutan' => 91],
            ['nama_kementerian' => 'Kementrian Koordinator Harta dan Kekayaan', 'kode_umap' => 92, 'urutan' => 92],
            ['nama_kementerian' => 'Kementrian Koordinator Korupsi dan Hukum', 'kode_umap' => 93, 'urutan' => 93],
            ['nama_kementerian' => 'Kementrian Koordinator Digitalisasi', 'kode_umap' => 94, 'urutan' => 94],
            ['nama_kementerian' => 'Kementrian Koordinator Sosial Masyarakat', 'kode_umap' => 95, 'urutan' => 95],
            ['nama_kementerian' => 'Kementrian Koordinator Pertahanan dan Militer', 'kode_umap' => 96, 'urutan' => 96],
            ['nama_kementerian' => 'Kementrian Koordinator DPR/MPR', 'kode_umap' => 97, 'urutan' => 97],
            ['nama_kementerian' => 'Kementrian Koordinator Pendidikan Nasional', 'kode_umap' => 98, 'urutan' => 98],
            ['nama_kementerian' => 'Kementrian Koordinator Ekonomi Nasional', 'kode_umap' => 99, 'urutan' => 99],
            ['nama_kementerian' => 'Kementrian Koordinator Infrastruktur Nasional', 'kode_umap' => 100, 'urutan' => 100],
            ['nama_kementerian' => 'Kementrian Koordinator Kehutanan Nasional', 'kode_umap' => 101, 'urutan' => 101],
            ['nama_kementerian' => 'Kementrian Koordinator Energi Nasional', 'kode_umap' => 102, 'urutan' => 102],
            ['nama_kementerian' => 'Kementrian Koordinator Pangan Nasional', 'kode_umap' => 103, 'urutan' => 103],
            ['nama_kementerian' => 'Kementrian Koordinator Kelautan Nasional', 'kode_umap' => 104, 'urutan' => 104],
            ['nama_kementerian' => 'Kementrian Koordinator Transmigrasi Nasional', 'kode_umap' => 105, 'urutan' => 105],
            ['nama_kementerian' => 'Tidak diketahui', 'kode_umap' => 106, 'urutan' => 106],
        ];

        foreach ($rows as $r) {
            MasterKementerian::updateOrCreate(
                ['kode_umap' => $r['kode_umap']],
                $r
            );
        }
    }
}
